### ISSUE TITLE
Config Server

### ISSUE THREAD

**Issue by jabrena** [jabrena/SpringCloudLab#41]
http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html

**Comment by jabrena** [comment]
``` bash
spring:
  cloud:
    config:
      server:
        health:
          repositories:
            myservice:
              label: mylabel
            myservice-dev:
              name: myservice
              profiles: development
```

**Comment by jabrena** [comment]
http://samchu.logdown.com/posts/292630-use-springcloud-to-synchronize-all-nodes-configuration

**Comment by jabrena** [comment]
https://github.com/spring-cloud/spring-cloud-config/issues/190

**Comment by jabrena** [comment]
https://dzone.com/articles/learning-spring-cloud

**Comment by jabrena** [comment]
https://dzone.com/articles/learning-spring-cloud

```
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
```
